### ISSUE TITLE
exempel action-panel stämmer inte med verkligheten

### ISSUE THREAD

**Issue by perut1** [Vastra-Gotalandsregionen/komponentkartan-demo#18]
exemplet för action-panel verkar inte stämma överrens med koden. Det står t.ex. 
> expanded: boolean | Anger om panelen ska vara öppen eller stängd. |  [expanded]="true"

medan i exemplet står det:
`[expanded]="expanded"`
Inget av dem fungerar dock i version 3.1.1 då verkar det vara `[open]="isopen" ` som gäller.

**Comment by AronssonFredrik** [comment]
Hej,
Det stämmer att `[open]="isOpen"` är korrekt. Detta syns även på APIn på Github sidan:

https://vastra-gotalandsregionen.github.io/komponentkartan-demo/actionPanels
